server:
  port: 80

spring:
  application:
    name: eureka-consunmer

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance: #主机名称：服务名称修改
    instance-id: consunmer
    prefer-ip-address: true #访问信息有ip信息提示

