server:
  port: 8099

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#mybatis全局配置
mybatis:
  type-aliases-package: com.zjmy.security.domain;
  mapper-locations: classpath:mapper/*/*.xml
  configLocation: classpath:mapper/mybatis-config.xml

