server:
  port: 8002  #服务端口号

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
spring:
  application:
    name: eureka-provider-atta #服务名称--调用的时候根据名称来调用该服务的方法
#数据源
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud
      username: root
      password: 123456
      initial-size: 5
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis全局配置
mybatis:
  type-aliases-package: com.zjmy.commons.domain;
  mapper-locations: classpath:mapper/*/*.xml
  configLocation: classpath:mapper/mybatis-config.xml
