eureka:
  instance:
    prefer-ip-address: true #注册服务的使用使用服务的ip地址
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8763  #服务端口号
spring:
  application:
    name: eureka-atta #服务名称--调用的时候根据名称来调用该服务的方法
#数据源
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dubbo_db
      username: root
      password: 123456
      initial-size: 5
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis全局配置
mybatis:
  type-aliases-package: com.zjmy.commons.domain;
  mapper-locations: classpath:mapper/*/*.xml
  configLocation: classpath:mapper/mybatis-config.xml
