server:
  port: 8001 #服务端口号

eureka:
  client:
    register-with-eureka: true #表识不向注册中心注册自己
    fetchRegistry: true  #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance: #主机名称：服务名称修改
    instance-id: provider8001
    prefer-ip-address: true #访问信息有ip信息提示

spring:
  application:
    name: eureka-provider-atta #服务名称--调用的时候根据名称来调用该服务的方法

#数据源
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud
      username: root
      password: 123456
      initial-size: 5
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis全局配置
mybatis:
  type-aliases-package: com.zjmy.commons.domain;
  mapper-locations: classpath:mapper/*/*.xml
  configLocation: classpath:mapper/mybatis-config.xml
