server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.147.131：1111  #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
