server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址 uri: http://localhost:8001
          #动态路由
          uri: lb://EUREKA-PROVIDER-ATTA
          predicates:
            - Path=/project/atta/** # 断言，路径相匹配的进行路由
            #- After=2020-10-23T16:23:15.064+08:00[Asia/Shanghai] #在这个时间之后
            #- Before=2020-10-23T16:23:15.064+08:00[Asia/Shanghai] #在这个时间之前
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://EUREKA-PROVIDER-ATTA
          predicates:
            Path=/project/atta/discovery/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版


